version: '3'
services:
  localstack:
    container_name: "spare-localstack"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway         
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "scripts:/etc/localstack/init/ready.d"
      - "data:/home/localstack/data"

volumes:
  scripts:  
  data: 